export const products = [
  {
    id: "1",
    name: "Classic White Tee",
    price: 29.99,
    image: "/whiteShirt.svg",
    description:
      "A timeless classic white t-shirt made from premium cotton. Perfect for everyday wear with a comfortable fit that lasts.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["White", "Black", "Gray"],
    material: "100% Organic Cotton",
    care: "Machine wash cold, tumble dry low",
    measurements: [
      { size: "XS", chest: "46 mm", length: "65 mm" },
      { size: "S", chest: "48 mm", length: "67 mm" },
      { size: "M", chest: "50 mm", length: "69 mm" },
      { size: "L", chest: "52 mm", length: "71 mm" },
      { size: "XL", chest: "54 mm", length: "73 mm" },
    ],
  },
  {
    id: "2",
    name: "Black Street Tee",
    price: 34.99,
    image: "/whiteShirt.svg",
    description:
      "Urban streetwear essential. This black tee features a modern cut and premium fabric for that street-ready look.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "White"],
    material: "100% Cotton",
    care: "Machine wash cold, hang dry",
    measurements: [
      { size: "XS", chest: "46 mm", length: "65 mm" },
      { size: "S", chest: "48 mm", length: "67 mm" },
      { size: "M", chest: "50 mm", length: "69 mm" },
      { size: "L", chest: "52 mm", length: "71 mm" },
      { size: "XL", chest: "54 mm", length: "73 mm" },
    ],
  },
  {
    id: "3",
    name: "Red Graphic Tee",
    price: 39.99,
    image: "/whiteShirt.svg",
    description:
      "Bold red graphic tee with unique artwork. Stand out from the crowd with this eye-catching piece.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Red", "Navy"],
    material: "100% Cotton",
    care: "Machine wash cold, tumble dry low",
    measurements: [
      { size: "S", chest: "48 mm", length: "67 mm" },
      { size: "M", chest: "50 mm", length: "69 mm" },
      { size: "L", chest: "52 mm", length: "71 mm" },
      { size: "XL", chest: "54 mm", length: "73 mm" },
    ],
  },
  {
    id: "4",
    name: "Minimalist Tank",
    price: 24.99,
    image: "/whiteShirt.svg",
    description:
      "Clean and simple tank top design. Perfect for layering or standalone wear during warmer months.",
    sizes: ["XS", "S", "M", "L"],
    colors: ["White", "Black", "Gray"],
    material: "100% Cotton",
    care: "Machine wash cold, hang dry",
    measurements: [
      { size: "XS", chest: "44 mm", length: "63 mm" },
      { size: "S", chest: "46 mm", length: "65 mm" },
      { size: "M", chest: "48 mm", length: "67 mm" },
      { size: "L", chest: "50 mm", length: "69 mm" },
    ],
  },
  {
    id: "5",
    name: "Oversized Hoodie",
    price: 59.99,
    image: "/whiteShirt.svg",
    description:
      "Comfortable oversized hoodie with a relaxed fit. Ideal for casual days and cooler weather.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Gray", "Navy"],
    material: "80% Cotton, 20% Polyester",
    care: "Machine wash cold, tumble dry low",
    measurements: [
      { size: "S", chest: "54 mm", length: "70 mm" },
      { size: "M", chest: "57 mm", length: "72 mm" },
      { size: "L", chest: "60 mm", length: "74 mm" },
      { size: "XL", chest: "63 mm", length: "76 mm" },
      { size: "XXL", chest: "66 mm", length: "78 mm" },
    ],
  },
  {
    id: "6",
    name: "Vintage Wash Tee",
    price: 32.99,
    image: "/whiteShirt.svg",
    description:
      "Pre-washed for that vintage look and feel. This tee has been treated to give it that worn-in appearance.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Light Blue", "Light Gray"],
    material: "100% Cotton",
    care: "Machine wash cold, hang dry",
    measurements: [
      { size: "XS", chest: "46 mm", length: "65 mm" },
      { size: "S", chest: "48 mm", length: "67 mm" },
      { size: "M", chest: "50 mm", length: "69 mm" },
      { size: "L", chest: "52 mm", length: "71 mm" },
      { size: "XL", chest: "54 mm", length: "73 mm" },
    ],
  },
];
